### ISSUE TITLE
error while building shaderc in the NDK

### ISSUE THREAD

**Issue by bpedazur** [googlesamples/vulkan-basic-samples#21]
Hi,
I'm using windows 10 and I can't run the command: "../../../ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_STL:=[gnustl_static|gnustl_shared|c++_static|c++_shared] APP_ABI=[armeabi-v7a|arm64-v8a|x86|x86_64|all] libshaderc_combined -j16". 
I get the error: "'gnustl_shared' is not recognized as an internal or external command, operable program or batch file.".

Thanks

**Comment by ggfan** [comment]
I may not get this today. Could you match the command into windows command line format, then execute it inside dos box.  Assuming you are in VS dev command line prompt, do something like this:
```
cd  %YOUR-NDK-HOME%\source\third_party\shaderc
..\..\..\ndk-build.cmd NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_STL=gnustl_static APP_ABI=all
```
this is because sample using gnustl_static, if you change it to use use c++_static, you will need to build that c++_static one -- in the above command, just change gnustl_static to c++_static.

The instruction is for Linux-like OSes, for windows, need translate them to windows format ( backslash/forwardslash, ndk-build vs ndk-build.cmd etc ).

give it a try and see how it goes.
